brianmay2014/debonairbnb

- README.md
- demo.html
- f-end/src/index.css
- f-end/src/theme.css
- notes.md
Set up CSS theme colors and button classes
> add css theme

- .env.example
- Pipfile
- Pipfile.lock
- app/config.py
- app/utils/s3utils.py
adds `s3utils.py` to the `utils` folder which will enable us to allow image uploads.
> add utils for aws s3 uploads

- react-app/package-lock.json
- react-app/public/index.html
- react-app/src/App.js
- react-app/src/components/NavBar/SearchBar/SearchBar.js
- react-app/src/components/NavBar/SearchBar/SearchDestinationInput/SearchDestinationInput.js
- react-app/src/components/SearchResults/SearchMap/SearchMap.js
- react-app/src/components/SearchResults/SearchResults.js
> Search google map

- react-app/src/App.js
- react-app/src/components/auth/LoginForm.js
- react-app/src/components/estate/CritiqueDisplay.js
- react-app/src/components/estate/EstatePage.js
- react-app/src/components/estate/IndCritique.js
- updated routes for protection on all routes
- username displays in critique displays on estate page
> updated routes, updated username display in critique display

- Dockerfile
- sarcastically extensive changes to the dockerfile
- attempting to fix docker deploy to heroku per deployment error message
> update docker file to try and deploy on heroku

- Dockerfile
> trying to update

- app/__init__.py
- react-app/src/store/estate.js
update __init__.py and estate fetch route inside store
> Brianmay2014 patch 2

- app/api/user_routes.py
- react-app/src/components/HostPage/EstateForm.js
- react-app/src/components/HostPage/EstateRow.js
- react-app/src/components/HostPage/HostPage.css
- react-app/src/components/HostPage/HostPage.js
- react-app/src/store/estate.js
- added estate image uploads for each owned estate
- added edit modal for estates, edit works and updates in database
- still needs validation and a prettier address upon update
> Edit estates

- react-app/src/components/estate/AvailabilityCal.js
- react-app/src/components/estate/CalendarFix.css
- fixed the css on the availability calendar
> update to fit 7 days on the calendar

- react-app/src/components/Charters/CharterPage/CharterPage.js
- react-app/src/components/SearchResults/SearchResults.js
- react-app/src/components/estate/AvailabilityCal.js
- react-app/src/components/estate/CharterForm.js
- react-app/src/utils/dateArrayCreator.js
redirects to user's charters once you've created a charter
> Charter refinement

- app/api/user_routes.py
- app/forms/custom_validators.py
- react-app/src/store/estate.js
testing to fix add estates on heroku
> testing backend route fix

- .env.example
- app/api/estate_routes.py
- app/config.py
be sure to add a REACT_APP_GOOGLE_MAPS_API_KEY to your .env file after this commit as per the env.example
on your development server, they can be the same.
> bifurcate api key between frontend and backend

- app/api/user_routes.py
- app/forms/custom_validators.py
- app/forms/estate_form.py
- app/utils/geoutils.py
- react-app/src/components/HostPage/EstateForm.js
- react-app/src/components/HostPage/EstateRow.js
- react-app/src/index.css
- react-app/src/store/estate.js
- added validators for address and nightly rate on edit and creating estates
-  emptied add form on a successful create estate
> Estate validate

- app/models/estate.py
- react-app/src/components/HomePage/HomePage.css
- react-app/src/components/HostPage/EstateRow.js
- react-app/src/components/HostPage/HostPage.css
- react-app/src/components/SearchResults/SearchResults.js
- react-app/src/components/estate/DescriptionAvailCharter.js
- react-app/src/components/estate/EstatePage.js
- react-app/src/components/estate/LocationDisplay.js
- react-app/src/components/estate/estatePage.css
> estate maps load with circle for estate zone

- react-app/src/components/HomePage/HomePage.css
- react-app/src/components/auth/AuthForms.css
- react-app/src/components/auth/LoginForm.js
- react-app/src/components/auth/SignUpForm.js
- updated the login and sign up form with
- - styling
- - errors displayed in format
- - links to the opposite page
- fixed the centering issue on the home page
> B login signup forms

- react-app/src/App.js
- react-app/src/components/HomePage/Footer.js
- react-app/src/components/HomePage/HomePage.css
- react-app/src/index.css
- react-app/src/theme.css
- added footer with about links
> footer and home page centering

- react-app/src/components/NavBar/NavBar.css
- react-app/src/components/NavBar/SearchBar/SearchBar.css
- react-app/src/components/NavBar/SearchBar/SearchBar.js
- react-app/src/components/NavBar/SearchBar/SearchDestinationInput/SearchDestinationInput.js
- react-app/src/components/NavBar/SearchBar/SearchDurationInput/SearchDurationInput.css
- react-app/src/components/NavBar/SearchBar/SearchDurationInput/SearchDurationInput.js
- update search after rebase
- date inputs are read only to match airbnb
- search bar look is minimized on nav bar
> B search 2

- app/forms/charter_edit_form.py
- app/models/charter.py
- react-app/src/components/Charters/CharterPage/CharterPage.css
- react-app/src/components/Charters/CharterPage/CharterPage.js
- react-app/src/components/Charters/CharterPage/EditModalTwo.js
- react-app/src/components/Charters/MyCharters/CharterRow.js
- react-app/src/components/Charters/MyCharters/EditForm/EditForm.js
- react-app/src/components/Charters/MyCharters/MyCharters.js
- react-app/src/components/NavBar/NavBar.css
- react-app/src/components/NavBar/ProfileButton/ProfileButton.css
- react-app/src/components/NavBar/ProfileButton/ProfileButton.js
- react-app/src/components/NavBar/SearchBar/SearchBar.css
- react-app/src/components/NavBar/SearchBar/SearchBar.js
- react-app/src/components/NavBar/SearchBar/SearchDestinationInput/SearchDestinationInput.js
- react-app/src/components/NavBar/SearchBar/SearchDurationInput/SearchDurationInput.js
- react-app/src/components/SearchResults/SearchMap/SearchMap.js
- react-app/src/components/SearchResults/SearchResults.css
- react-app/src/components/SearchResults/SearchResults.js
- react-app/src/components/estate/AvailabilityCal.js
- react-app/src/components/estate/CharterForm.js
- react-app/src/components/estate/estatePage.css
- search bar returns message with search result destination and handles no results
- multiple css tweaks
- formatted all currency
- sorted charters page by created at date
- diamond icons now clickable with link to estate page on search map
> Bug fixing

- react-app/src/components/Charters/MyCharters/CharterRow.js
-update css file inside CharterRow
> update css file link

- react-app/src/components/NavBar/SearchBar/SearchBar.js
- react-app/src/components/SearchResults/SearchResults.js
Granted everything works well, this will be my last request.
> fixed bug with search dates, should be good now!

- app/api/charter_routes.py
- app/api/estate_routes.py
- app/config.py
- app/forms/charter_edit_form.py
- app/forms/charter_form.py
- app/utils/geoutils.py
- react-app/src/components/Charters/CharterPage/CharterPage.js
- react-app/src/components/Charters/CharterPage/EditModalTwo.js
- react-app/src/components/Charters/MyCharters/EditForm/EditForm.js
- react-app/src/components/HostPage/EstateForm.js
- react-app/src/components/HostPage/EstateRow.js
- react-app/src/components/NavBar/ProfileButton/ProfileButton.js
- react-app/src/components/NavBar/SearchBar/SearchBar.js
- react-app/src/components/SearchResults/SearchMap/SearchMap.js
- react-app/src/components/UploadImage/UploadeImage.js
- react-app/src/components/auth/LogoutButton.js
- react-app/src/components/estate/CharterForm.js
- react-app/src/store/charter.js
- react-app/src/store/critique.js
- react-app/src/store/estate.js
- react-app/src/store/estateType.js
- removing console.logs and prints
- updating the profile dropdown menu to be gone after logging out
> Remove logs

- react-app/src/components/NavBar/SearchBar/SearchBar.js
search bar value now displayed 'search states' at home page.
> updated state of search bar value for homepage
